In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data=pd.read_csv('zomato.csv',encoding='latin-1')  #encoding is exported in latin-1 format

In [3]:
data.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [4]:
data.shape

(9551, 21)

In [5]:
data.columns   #average cost for two is the y value while others are x value

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [6]:
#delete unnecessary columns
data.drop(columns=['Restaurant ID','Is delivering now','Switch to order menu','Rating color','Rating text'],inplace=True)

In [7]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [8]:
data=data[data['Country Code']==1]

In [9]:
data.shape

(8652, 16)

In [10]:
data['Country Code'].value_counts()

1    8652
Name: Country Code, dtype: int64

In [11]:
data["City"].value_counts()

New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Guwahati          21
Lucknow           21
Amritsar          21
Bhubaneshwar      21
Ahmedabad         21
Coimbatore        20
Pune              20
Ludhiana          20
Goa               20
Allahabad         20
Mangalore         20
Vizag             20
Mysore            20
Kanpur            20
Puducherry        20
Chennai           20
Nagpur            20
Varanasi          20
Kochi             20
Surat             20
Ranchi            20
Aurangabad        20
Indore            20
Agra              20
Dehradun          20
Bangalore         20
Jaipur            20
Nashik            20
Patna             20
Kolkata           20
Vadodara          20
Mumbai            20
Bhopal            20
Hyderabad         18
Chandigarh        18
Secunderabad       2
Panchkula          1
Mohali             1
Name: City, dtype: int64

In [12]:
data=data[data['City'].isin(['New Delhi','Gurgaon','Noida','Faridabad'])]

In [13]:
data.shape

(7922, 16)

In [14]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [15]:
#second round of screening of data
data.drop(columns=['Restaurant Name','Country Code','Address','Locality','Locality Verbose','Currency'],inplace=True)

In [16]:
data.shape

(7922, 10)

In [17]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [18]:
data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)

In [19]:
data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)

In [20]:
data.shape

(7922, 10)

In [21]:
data.corr()['Average Cost for two']

Longitude               0.071752
Latitude                0.070993
Average Cost for two    1.000000
Has Table booking       0.642966
Has Online delivery     0.076953
Price range             0.847985
Aggregate rating        0.328440
Votes                   0.299089
Name: Average Cost for two, dtype: float64

In [22]:
#3rd round of screening
data.drop(columns=['Has Online delivery','Price range'],inplace=True)

In [23]:
data.shape

(7922, 8)

In [24]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Aggregate rating', 'Votes'],
      dtype='object')

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7922 entries, 865 to 9112
Data columns (total 8 columns):
City                    7922 non-null object
Longitude               7922 non-null float64
Latitude                7922 non-null float64
Cuisines                7922 non-null object
Average Cost for two    7922 non-null int64
Has Table booking       7922 non-null int64
Aggregate rating        7922 non-null float64
Votes                   7922 non-null int64
dtypes: float64(3), int64(3), object(2)
memory usage: 557.0+ KB


In [26]:
#label encoding is the conversion of strings in terms of 0 and 1
#the deletion of last column after 'label encoding' is called one hot encoding
data.head()

City  Longitude   Latitude                    Cuisines  \
865  Faridabad  77.306640  28.490059  Chinese, Fast Food, Bakery   
866  Faridabad  77.304776  28.490157       North Indian, Chinese   
867  Faridabad  77.305563  28.490137                North Indian   
868  Faridabad  77.306102  28.490098                North Indian   
869  Faridabad  77.305745  28.490062                      Bakery   

     Average Cost for two  Has Table booking  Aggregate rating  Votes  
865                   250                  0               2.9      4  
866                   500                  0               2.8     16  
867                   150                  0               2.8      8  
868                   150                  0               2.9      8  
869                   100                  0               2.8      7

In [27]:
a=data.groupby('Cuisines')['Average Cost for two'].mean().sort_values(ascending=False).reset_index()

In [28]:
data=data.merge(a,on='Cuisines')

In [29]:
data.drop(columns=['Cuisines'],inplace=True)

In [30]:
data.head()

City  Longitude   Latitude  Average Cost for two_x  Has Table booking  \
0  Faridabad  77.306640  28.490059                     250                  0   
1  New Delhi  77.049525  28.806199                     500                  0   
2  Faridabad  77.304776  28.490157                     500                  0   
3  Faridabad   0.000000   0.000000                     300                  0   
4  Faridabad  77.305698  28.471985                    1200                  1   

   Aggregate rating  Votes  Average Cost for two_y  
0               2.9      4              375.000000  
1               0.0      0              375.000000  
2               2.8     16              594.303797  
3               0.0      0              594.303797  
4               0.0      0              594.303797

In [31]:
data.rename(columns={'Average Cost for two_x':'cost','Average Cost for two_y':'cuisines'},inplace=True)

In [32]:
data.head()

City  Longitude   Latitude  cost  Has Table booking  Aggregate rating  \
0  Faridabad  77.306640  28.490059   250                  0               2.9   
1  New Delhi  77.049525  28.806199   500                  0               0.0   
2  Faridabad  77.304776  28.490157   500                  0               2.8   
3  Faridabad   0.000000   0.000000   300                  0               0.0   
4  Faridabad  77.305698  28.471985  1200                  1               0.0   

   Votes    cuisines  
0      4  375.000000  
1      0  375.000000  
2     16  594.303797  
3      0  594.303797  
4      0  594.303797

In [33]:
data.corr()['cost']

Longitude            0.071752
Latitude             0.070993
cost                 1.000000
Has Table booking    0.642966
Aggregate rating     0.328440
Votes                0.299089
cuisines             0.808274
Name: cost, dtype: float64

In [34]:
y=data.iloc[:,3].values

In [35]:
y

array([ 250,  500,  500, ...,  450, 1000,  450], dtype=int64)

In [36]:
X=data.drop(columns=['cost']).iloc[:,:].values

In [56]:
X.shape

(7922, 9)

In [38]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [39]:
X[:,0]=encoder.fit_transform(X[:,0])   #label encode kar diya for cities

In [40]:
X

array([[0, 77.3066401, 28.4900591, ..., 2.9, 4, 375.0],
       [2, 77.04952508, 28.80619877, ..., 0.0, 0, 375.0],
       [0, 77.304776, 28.490156699999996, ..., 2.8, 16,
        594.3037974683544],
       ...,
       [3, 77.3648332, 28.5971027, ..., 3.5, 105, 450.0],
       [3, 77.32321292, 28.567750899999997, ..., 0.0, 0, 1000.0],
       [3, 77.32530809999999, 28.5671503, ..., 2.0, 161, 450.0]],
      dtype=object)

In [41]:
X[:,0]

array([0, 2, 0, ..., 3, 3, 3], dtype=object)

In [42]:
X.shape

(7922, 7)

In [43]:
from sklearn.preprocessing import OneHotEncoder
oencoder=OneHotEncoder(categorical_features=[0])

In [44]:
X=oencoder.fit_transform(X).toarray()

C:\Users\Purbita\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Purbita\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [45]:
X.shape

(7922, 10)

In [46]:
X[:,0:4]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [47]:
X=X[:,1:]

In [48]:
X.shape

(7922, 9)

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=7)

In [50]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()

In [51]:
regressor1.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [52]:
from sklearn.metrics import r2_score

In [53]:
y_pred=regressor1.predict(X_test)

In [54]:
r2_score(y_test,y_pred)*100

69.45487835658287